version: '3'
services:
  musicify-app:
    build: .
    container_name: node-musicify-app
    depends_on:
      - musicify-postgres
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=node-musicify-database
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - musicify-bridge
    volumes:
      - type: bind
        source: ./
        target: /app/musicify/
      - /app/musicify/node_modules
    restart: always

  musicify-postgres:
    build: ./database/
    container_name: node-musicify-database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - musicify-bridge
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

networks:
  musicify-bridge:
    name: musicify-bridge
    driver: bridge

volumes:
  database:
